"""Original IELTS-style reading passages (not from copyrighted papers)."""

from __future__ import annotations

AC_P1 = """Urban heat islands form when cities replace vegetation with asphalt, concrete and dense buildings that absorb and re-radiate heat. Night-time temperatures in central districts can remain several degrees higher than in surrounding rural areas. Researchers distinguish surface heat islands, measured by satellite, from canopy heat islands, measured a few metres above street level. Both matter for public health: prolonged heatwaves increase hospital admissions for respiratory and cardiovascular conditions, especially among older residents and outdoor workers. The distinction is not academic. A neighbourhood can look cool on a satellite map if trees hide hot roofs, yet still trap heat at pavement height where people actually walk.

Mitigation is rarely a single intervention. Reflective (cool) roofs lower surface temperatures but may reflect heat onto neighbouring pedestrians unless street trees or shade structures accompany them. Green roofs retain stormwater and cool through evapotranspiration, yet they require structural loading capacity and maintenance budgets that many older buildings lack. Street trees deliver shade and psychological benefits, but underground utilities often constrain planting pits. Light-coloured paving and “cool” asphalt mixes can reduce stored heat, though they scuff faster in bus lanes. Policy success therefore depends on matching tools to local constraints rather than importing a fashionable solution wholesale. Cities that copied a Mediterranean courtyard programme onto dense high-rise streets found the courtyards too small to move air, and the budget was spent before a single tree pit was enlarged.

A further complication is equity. Heat risk maps frequently show higher exposure in lower-income neighbourhoods with fewer parks and more industrial land use. Without deliberate targeting, city-wide cool roof subsidies can favour owners of large commercial properties who already have facilities teams to file applications. Renters, who cannot alter a roof they do not own, are left with hotter interiors and higher cooling bills. Several municipalities now combine mandatory cool-roof codes for new warehouses with free tree vouchers for streets that exceed a measured heat threshold. Community groups argue that vouchers still fail if planting is left to residents who work night shifts; they want the city to plant and water for the first three years.

Early evaluations of these combined programmes suggest modest night-time cooling of 0.5–1.5°C on treated blocks, which is small in absolute terms but meaningful during multi-day heat events. The same studies warn that daytime peaks change less unless shade is added at street level. Instrumentation is itself a political choice: sensors placed on civic buildings under-report heat in laneways behind warehouses. A fair evaluation therefore needs sensors where people wait for buses, not only where engineers find a power socket. Some critics say a 1°C change is not worth the cost; public-health researchers reply that emergency-department data move even when the thermometer barely does, because humidity and overnight recovery matter as much as the daily maximum.

Heat policy also intersects with flood control and air quality. Vegetation that cools a street can slow stormwater and trap particles, but only if species are chosen for drought and for roots that will not lift pavements. Cool roofs that reduce air-conditioning demand also cut peak electricity load, which in several cities is still met by gas plants on the hottest afternoons. That co-benefit is often omitted from heat-island budgets, making trees look expensive when they are in fact paying twice. The writer’s conclusion is practical rather than utopian: treat heat as a design and justice problem, measure it at the height of a pedestrian, and refuse to call a programme a success merely because a roof looks white from space.

A last constraint is maintenance. A cool coating that is not recoated after ten years becomes an ordinary grey roof; a tree that dies in the second summer becomes a stump that residents remember as a broken promise. Cities that budget only for installation, not for watering contracts and inspection, quietly recreate the inequality they claimed to fix: richer streets water their own trees, poorer streets watch them fail. Some public-health teams now treat a living canopy as they would a clinic — scheduled visits, a named officer, and a number to call when a pit is dry. That sounds bureaucratic, and it is the difference between a press release and a cooler night. Researchers also note that heat is not only a summer story. Mild winters in sealed neighbourhoods can keep night temperatures high enough that indoor mould and poor sleep persist, which is why year-round monitoring is replacing a single August campaign. None of this requires a miracle material. It requires the unglamorous work of matching tools to streets, paying for the decade after the photograph, and counting patients as well as pixels."""

AC_P2 = """The honey bee (Apis mellifera) has long been studied for its social organisation. Colonies contain a single queen, thousands of workers, and, seasonally, drones. Workers perform age-related tasks: young bees clean cells, middle-aged bees nurse larvae, and older bees forage. This sequence, known as temporal polyethism, is flexible. If nurse bees are removed, some foragers can reactivate brood-food glands, though the colony pays a cost in reduced incoming nectar. Communication about food sources relies on the waggle dance, which encodes distance and direction relative to the sun. Recruits do not follow the dancer into the field; they fly independently using the encoded vector, which is why a small number of scouts can mobilise hundreds of workers within an hour.

Recent research suggests that pesticide exposure can impair navigation even when acute mortality remains low. Sub-lethal doses of certain neonicotinoids lengthen foraging trips and increase the chance that a bee will fail to return. Conservation programmes therefore focus on habitat corridors and reduced chemical load rather than hive numbers alone. Planting a strip of wildflower between two orchards sounds simple, yet the strip must bloom in the weeks when crop flowers do not, or it merely concentrates bees during spraying. Timing, not just area, determines whether a corridor is a refuge or a trap.

Commercial pollination contracts have grown with monoculture agriculture, creating economic incentives to keep large migratory operations. Hives are trucked from almond groves to berry fields in a calendar that leaves little forage in between. Critics argue that treating bees primarily as livestock overlooks wild pollinators that provide complementary services but receive less policy attention. Bumblebees, hoverflies and solitary bees often work in cooler hours or on flowers that honey bees ignore. When a single species is asked to pollinate an entire landscape, disease and food shortages travel with the trucks.

Disease management inside commercial yards is itself a moving target. Varroa mites weaken bees and spread viruses; treatments that once worked now fail in some regions as mites evolve resistance. Beekeepers rotate compounds and breed for hygienic behaviour — workers that detect and remove infested pupae — but those traits can reduce honey yield, which contracts rarely reward. A colony that survives a winter with a smaller store may still be the more valuable animal in a landscape full of mites. Researchers also note that nutrition, not only chemicals, shapes immunity: protein-poor pollen in intensive almond weeks leaves bees less able to handle a later virus pulse.

The policy implication is uncomfortable for anyone who wants a single lever. Increasing hive counts can raise almond yields this season while crowding wild bees off the remaining forage. Reducing spray windows helps both, but growers fear a missed application more than a missed bee. The writer does not claim that commercial beekeeping should end. The claim is narrower: hive numbers are a poor proxy for pollination health, and programmes that ignore navigation, nutrition and wild species will keep reporting more boxes on trucks while the landscape quietly loses the insects that do not have a contract.

Public debate often collapses this into a question of whether shoppers should “save the bees” by buying a jar of local honey. Honey purchases can support a careful beekeeper; they cannot rebuild a hedge, and they do nothing for a hoverfly. School projects that install a single hive on a playground roof sometimes increase stings and local swarming without adding forage. The more useful civic act is unfashionable: leave a strip unmown, delay spraying until after dusk, and fund the monitoring that tells a grower whether a corridor is actually used. Scientists still disagree about how far a worker will fly when nearby forage is poor, which is why corridor width is a live research question rather than a slogan. What is not in dispute is the waggle dance itself: it encodes distance and direction, not flower colour, and a scout that cannot navigate home is a lost investment whether or not the colony’s headcount looks healthy on a spreadsheet."""

AC_P3 = """Open science advocates argue that publicly funded research should be freely readable. Traditional subscription journals, they claim, create access barriers for scholars in under-resourced institutions. A researcher who cannot log in from a campus without a big package deal may reinvent an experiment that already failed, or miss a method that would have saved months. Article Processing Charges (APCs) shift costs to authors or their funders, which can exclude early-career researchers without grants. The fee is often framed as the price of freedom, yet it simply relocates the toll booth from the reader to the writer.

Hybrid journals that offer both subscription access and optional open access have been criticised for “double dipping” when libraries still pay for packages while authors also pay APCs. Publishers reply that hybrids are a bridge, not a destination, and that subscription prices will fall as more articles become open. Independent analyses of large deals have found little evidence of that decline so far. Meanwhile, fully open journals vary wildly in quality: some are community-run and rigorous; others send acceptance letters before review. The existence of predatory titles is then used, unfairly, to smear every APC-funded venue.

Some disciplines have adopted preprint servers aggressively; others remain cautious about priority disputes and the absence of peer review prior to posting. Physicists have used arXiv for decades; parts of the humanities still treat a public draft as a risk to a later book contract. Funders in several countries now require deposit of accepted manuscripts in repositories within a defined embargo. Whether these mandates improve citation equity remains debated: early evidence shows increased downloads, but citation advantages vary by field and language. English-language biomedical papers appear to gain more than regional social-science work, which may simply reflect who is already indexed in the databases used to count citations.

A quieter issue is data. Opening the PDF without opening the spreadsheet still leaves replication expensive. Journals that require data deposits discover that many datasets are too messy to share, or are locked by industry partners. Some authors post a “available on request” note that is never answered. Reviewers, unpaid and overworked, rarely check whether a repository link still resolves a year later. The infrastructure of open science — persistent identifiers, licences, and curators who can reject a dump of untitled files — costs money that APCs do not automatically fund.

The writer’s position is not that every paper must be free tomorrow on the same platform. It is that access barriers at under-resourced institutions are real, that APCs can reproduce those barriers on the author side, and that hybrid titles have not yet proved they will stop charging twice. Mandates that only count PDFs will miss the harder work of sharing data and reviewing it. Equity, in this view, is a design problem for the whole communication system, not a badge on the first page of an article.

Libraries, meanwhile, are asked to cancel packages they still need for the hybrid remainder, then to celebrate a “transformative” deal whose small print keeps the most-read titles behind a delay. Early-career researchers without grants face a second barrier: they can read an open paper and still be unable to publish a reply because the APC exceeds a month’s stipend. Some learned societies have kept dues-funded journals with no author fee; those titles are rarely the ones that hiring committees count. The citation evidence is messy for a reason. Downloads can rise because a paper is assigned in a large undergraduate course, not because a scholar in a second language suddenly gained an equal chance of being cited. Funders that treat a repository PDF as the whole of open science will keep missing the unpaid labour of review and the broken links to data. The passage does not offer a single vendor as the solution. It asks whether the toll booth has moved, and who is still standing outside."""

AC_P4 = """Mechanical recycling of plastic works only when waste streams are relatively clean. A bottle collected from a household bin may be coated with food residue, mixed with a different polymer, or dyed in a way that makes the resulting pellet unattractive to manufacturers. Even a small share of PVC in a PET bale can ruin a batch destined for new bottles. Chemical recycling — breaking polymers back into feedstock — is often presented as the missing piece, but plants remain expensive and energy-hungry, and independent audits have found that some facilities still send a large share of input to incineration. The word “recycling” on a warehouse door does not, by itself, tell an auditor where the carbon in that plastic went.

Policy has shifted from voluntary pledges to recycled-content mandates. Several jurisdictions now require that new beverage bottles contain a minimum percentage of recycled plastic by 2030. Brands argue that collection systems cannot yet supply enough food-grade material; waste operators reply that demand was weak for years, so sorting lines were never built. Without both a stable buyer and cleaner collection, mandates risk raising prices without cutting virgin production. A supermarket that prints “30% recycled” on a bottle still needs a virgin stream for the rest, and if collection stays dirty the recycled share is met by importing pellets from somewhere else, not by emptying local bins.

A quieter constraint is design. Multi-layer pouches and black plastic trays are technically recyclable in laboratories yet rejected by optical sorters. Carbon-black pigment, used to make trays look premium, absorbs the infrared signal that separators use to identify polymer type. Design-for-recycling rules, which limit certain pigments and adhesives, may do more for actual recovery rates than new plants. Critics of this view say it underestimates the volume of existing stock already in circulation. Both can be true: tomorrow’s packaging can be simpler while yesterday’s waste still needs an honest end-of-life route that is not labelled recycling when it is not.

Household behaviour is the other half of the machine, and it is poorly designed for. Labels that say “check locally” outsource the sorting decision to a resident who cannot see inside the materials recovery facility. When a city changes which plastics it accepts, the old leaflet stays on the fridge. Contamination then becomes a moral story about careless people rather than a story about mixed messages. Some municipalities now print a single “yes/no” list on the bin lid and ban the chasing-arrows symbol on non-recyclable film. Early trials show cleaner bales, not because residents suddenly studied polymer chemistry, but because the interface stopped lying.

The writer does not treat chemical plants as villains or heroes. They may have a role for films that mechanical lines cannot handle, provided the energy cost is published and incineration is not relabelled as “feedstock recovery”. What the passage insists on is vocabulary. If a facility burns most of what it receives, it is an energy plant with a recycling press release. If a mandate raises prices while virgin production stays flat, it is a labelling exercise. Recovery that actually returns a bottle to a bottle still depends on clean streams, honest design, and demand that lasts longer than a campaign.

Exporters used to ship mixed bales overseas and call the result recycling because the paperwork said so. Several importing countries have since tightened rules, which pushed low-grade film back onto domestic yards that were never built for it. That shock is useful: it made the gap between a laboratory test and a sorter’s camera impossible to ignore. Black trays and multi-layer pouches failed in public, not only in a journal. Brands that had printed a chasing-arrows symbol on film that no city accepted were forced to redesign or to drop the claim. The 2030 bottle mandates will not, by themselves, invent food-grade pellet supply. They can, if paired with design rules and a buyer who will still be there in 2031, make a clean stream worth collecting. Without that pair, the audit will keep finding incineration at the back of a building that faces the street with the word recycling."""

AC_P5 = """Remote work expanded fastest in occupations that already used email, shared documents and video calls. Surveys after 2020 found higher reported job satisfaction among those who could choose a hybrid pattern, but also longer working hours and more meetings. The extra hour that used to be a commute often became another call. Productivity studies disagree: some firm-level data show stable output, while call-centre experiments found slower handling times when staff were fully remote. The clash is less mysterious than it looks. A lawyer billing by the case and an agent measured by average handle time are not in the same labour market, even if both sit on Zoom.

The distribution of benefits is uneven. Parents of young children often value the commute time recovered, yet they also report more interruptions. Junior staff in some industries said they received less informal mentoring — the overheard conversation that used to explain how a client actually likes a report. Cities that relied on office lunches and rail season tickets saw sharper drops in footfall than cities with mixed residential centres. Policymakers now debate whether to freeze commercial rates, convert empty floors to housing, or wait for a rebound that may not arrive at 2019 levels. A vacant tower is not automatically a block of flats: plumbing, fire rules and owners’ loans all intervene.

Hybrid arrangements have become the compromise, typically two or three office days. Managers claim this protects culture; employees often treat the office days as meeting-heavy and keep deep work for home. Whether this split is efficient depends on the task. Research that treats “remote” as a single condition is therefore misleading. The relevant question is which activities need co-location, and how organisations measure output without counting hours at a desk. Pair programming, studio critique and some kinds of apprenticeship still suffer on a laptop. Writing a specification, by contrast, often improves when the calendar is empty.

Infrastructure quietly decides who can take the bargain. A spare room, fast broadband and a door that closes are not evenly supplied. Staff who share a one-bedroom flat, or who live in a region with expensive mobile data, experience “remote” as a tax. Some firms reimbursed chairs in 2020 and then stopped, leaving the cost on the household. Unions have begun to treat home working as a workplace that needs inspection, not a perk that cancels labour law. That argument is unfinished, but it explains why satisfaction scores and burnout scores can rise together.

The writer’s caution is against fashion. Fully remote, fully office, and hybrid are tools, not identities. A call-centre experiment that found slower handling times does not prove that designers should commute five days a week. A survey that found higher satisfaction does not prove that juniors are learning. Measure the activity, not the slogan, and notice who is missing from the sample: the people who never had a desk job to take home.

Managers who count badge-swipes will always prefer a full office, because presence is easy to audit. Managers who count shipped work can tolerate a quieter building. The fight between those two measurement cultures is older than video calls; the pandemic only made it visible. Cities, for their part, cannot wait for a single national answer. A rail town that lost season tickets is not the same as a mixed centre where the café was never only for office lunch. Converting empty floors to housing is slow, legally messy, and still more honest than pretending 2019 will return if the mayor asks nicely. The passage’s last distinction is simple. Remote work is not a personality. It is a set of tasks, a set of rooms, and a set of costs that someone — firm, household, or city — will pay."""

AC_P6 = """Coral reefs occupy a small fraction of the ocean yet support a disproportionate share of marine species. They also protect coasts by breaking wave energy before it reaches villages and hotels. When sea temperatures stay high for weeks, corals expel the algae that feed them and turn white — the event called bleaching. A bleached coral is not immediately dead, but repeated events leave less time to recover. In several regions, the interval between severe bleaching years has shortened from decades to a handful of years, which is faster than many species can migrate or adapt.

Restoration projects now include coral gardening: fragments are grown in nurseries and transplanted onto damaged reefs. Survival rates vary with water quality, anchoring method and whether local fish still graze the algae that would otherwise smother young colonies. Gardening is labour-intensive and cannot keep pace with a basin-scale heatwave. Its defenders argue that it buys time and trains local teams, not that it replaces emissions cuts. Critics call it a photogenic distraction. Both descriptions can be true of the same project, depending on whether the press release mentions climate or only the number of fragments tied to a frame.

A second line of work selects corals that already survive warmer water and breeds them. The ethics are contested. Introducing a heat-tolerant strain into a reef may raise the odds of surviving the next summer and still reduce genetic diversity that would have helped against disease. Communities that depend on a reef for food want the fish back this decade; geneticists want a longer trial. Permitting systems rarely hold both clocks. Meanwhile, sewage and sediment from coastal building continue to stress reefs that no breeding programme can rescue if the water stays cloudy.

Tourism complicates the ledger. Divers pay for moorings that reduce anchor damage, and some fees fund rangers. The same boats, poorly managed, break coral and stir sediment. A resort that advertises a “restored reef” a few metres from an untreated outfall is selling a photograph, not a habitat. Certification schemes try to distinguish the two, but travellers rarely read the audit. Governments that count tourist arrivals as success and reef cover as a footnote will keep approving rooms on the dune.

The passage does not claim that gardening or breeding is useless. It claims that restoration without cooler water and cleaner coasts is a delay tactic, and that delay tactics still have a human value if they keep a fishery alive while politics catch up. What it refuses is the swap in which a nursery frame becomes an excuse to postpone the harder work of sewage, sediment and emissions. A reef can be both a garden and a warning, but only if the warning is allowed to appear in the same brochure as the garden.

Local knowledge is not a footnote to these programmes. Fishers often know which bays bleach first and which shelves still hold shade at noon. Projects that hire them as technicians, not as mascots, tend to keep fragments alive through the first monsoon. Projects that fly in a team for a filming week tend to leave frames that storm debris later buries. None of that substitutes for the physics of warm water. It does decide whether a community still has a reason to guard a reef that tourists photograph and then leave. The interval between severe bleaching years has shortened; that sentence belongs in the brochure, next to the count of fragments tied this season. If it does not, the garden is a costume."""

GT_S1 = """City Leisure Centre — Membership leaflet

Standard membership: £32 per month or £340 per year (save £44). Includes gym, swimming pool and group fitness classes. Bring photo ID on your first visit. Under-16s need a parent or guardian signature. Personal training is not included; book those sessions separately at reception.

How to join: complete Form LC-12 at reception or online. Direct debit starts on the 1st of the following month. Cancel with 30 days’ written notice. Lost cards cost £5 to replace. Free induction sessions run Tuesdays and Thursdays at 11:00 — book at least 24 hours ahead.


Pool and peak-hour notice

Peak hours: weekdays 06:30–09:30 and 17:00–20:00. Pool lanes 1–2 are reserved for members during peak; lanes 3–4 are for swim school. Weekend peak is Saturday 09:00–12:00 only. The learner pool closes every first Monday for plant maintenance.

Towels are not provided. Please shower before entering the water. Outdoor shoes are not allowed on poolside. A parent must stay with children under 8 in the water.


Lockers, café and parking

Lockers require a £1 coin refundable deposit. Overnight bags are not permitted; uncollected items go to lost property after 48 hours. The café opens at 07:30 on weekdays and 09:00 at weekends. Cycle racks are at the north entrance; car parking is pay-and-display after 10:00."""

GT_S2 = """Internal memo — Riverside Logistics
To: Warehouse team leads
From: Operations
Subject: New shift handover checklist (effective Monday)

Please ensure outgoing supervisors complete the digital handover form before leaving site. Required fields: incident log (even if “none”), open dock doors, refrigerated bay temperature, and keys signed out.

Temperature for chilled bay C must stay between 2°C and 5°C. If the reading is outside this range for more than 15 minutes, call the on-call engineer (ext. 440) and note the time in the form. Do not transfer stock to bay D without written authorisation from the night manager.

Visitors must wait in reception; high-visibility vests are mandatory past the yellow line. Personal phones are prohibited in the picking zone during night shifts. Report near-misses within 24 hours using portal RL-SAFE.

Forklift keys stay in the locked cabinet in the team-lead office, not in vehicles. If a pallet wrap machine jams, isolate power before calling maintenance. Do not use bay D as overflow for chilled goods even if bay C looks full — that bay is ambient storage only.

Night managers will audit three handovers per week at random. Incomplete forms count as a safety incident, not an admin slip. Training for the new form is 20 minutes on the intranet; complete it before your next night shift."""

GT_S3 = """For decades, local libraries were judged mainly by how many books they lent. Today many librarians describe their role as supporting “information confidence” — helping people judge sources, complete online forms, and access public services that have moved behind digital doors. In towns where bank branches and council desks have closed, the library often becomes the last free indoor place with wifi, printers and staff who will sit with a confused user for twenty minutes.

This shift is uneven. Well-funded city systems run coding clubs and maker spaces; rural branches may open only three afternoons a week and rely on volunteers. National statistics that celebrate rising digital session counts can hide the fact that print borrowing still matters most for children under eight and for readers who cannot afford devices. Campaigners therefore urge funders to measure outcomes such as successful benefit applications assisted, not only wifi hours logged.

Staff training has not always kept up. A librarian hired to recommend novels may now be asked to explain a housing portal that changes its password rules every quarter. Some systems hire digital-help assistants on short contracts; others simply add the work to the existing desk. Burnout shows up as shorter opening hours, which then look, in the next budget, like proof that demand is falling.

Critics worry that mission creep turns libraries into unofficial social-work offices without training or safeguarding resources. Supporters reply that refusing help with a housing form is itself a choice — one that pushes vulnerable residents toward paid intermediaries. The practical middle path emerging in several regions is partnership: librarians handle navigation and appointments; specialist charities take complex cases. Where that partnership is funded, doorstep evictions linked to missed online forms decline. Where it is not, the wifi statistics still look healthy, and the people who needed a person never appear in the count.

Print collections remain the quiet majority of what children actually take home. A tablet club that photographs well does not replace the stack of picture books by the door. The writer’s argument is that libraries are being asked to be two institutions at once, and that only one of those institutions is cheap to count. If funders want the civic one — the twenty minutes with a confused user — they have to budget for staff time, not only for broadband."""

GT_S4 = """Westbridge Job Club — this week’s vacancies

Reception assistant, Westbridge Clinic. 20 hours a week, Monday–Friday mornings. Must be comfortable with a phone system and booking software. First-aid certificate useful but not essential; training provided. Apply with form WB-04 by Friday 18th.

Warehouse picker, North Gate Foods. Night shifts 22:00–06:00. Steel-toe boots supplied. Previous forklift licence preferred. Minimum age 18. Text NIGHT plus your name to 07700 900882.

Café supervisor, Canal Museum. Full time. Food-hygiene certificate required before start date. Include two references. Interviews on 3 March in the museum education room, not at the café itself.


Notice: bus replacement

From Monday 12 May, the 14A will not stop at Job Club during roadworks on Station Road. Use stop C on Market Square, a four-minute walk. A shuttle from the square runs at 08:50 and 12:20 on weekdays only.


Lost property

A black rucksack was handed in at reception on Tuesday. Describe the contents to claim it. Uncollected items are sent to the charity shop after 14 days."""

GT_S5 = """Staff handbook extract — Harbour View Hotel

Uniforms: front-of-house staff wear the navy jacket provided. Laundry is on-site; do not take uniforms home. Kitchen whites are changed at the start of each shift. Name badges stay at the staff desk overnight.

Breaks: shifts over six hours include a 30-minute unpaid break. Take breaks in the staff room, not in guest corridors. Phone use is allowed in the staff room only.

Keys: room keys are issued against a signature. If a guest is locked out after 23:00, call night security on extension 201, not the restaurant. Never leave a master key in a door.

Fire: assembly point is the far end of Car Park B, not the main entrance. Weekly alarm tests are Tuesdays at 10:00. If you hear the alarm at any other time, evacuate.

Reporting: guest complaints about noise go on form HV-12. Maintenance faults go to the tablet on the housekeeper’s trolley, not to WhatsApp groups. Cash tips are recorded in the till, not in pockets."""

GT_S6 = """Night markets are often described as a tourist spectacle, but for many cities they are first a labour market. Stallholders rent a few square metres, bring a generator or tap a shared cable, and sell food that would not survive a high-street lease. The same markets also organise social time: families eat standing up after late shifts, and students revise under the same lights that advertise noodles. When a council treats the market only as a brand, it tends to raise pitch fees, standardise stalls, and push out the vendors who cannot afford a matching awning.

Hygiene rules are not the enemy of this economy, but they are often written for kitchens with sinks and staff rotas. A cart that moves each night cannot plumb a grease trap to the standard of a restaurant. Cities that want both safety and survival invent intermediate licences: sealed water tanks, inspected once a month, instead of a full commercial kitchen. Where that licence does not exist, enforcement arrives as a raid, and the market empties for a week before returning two streets away.

Residents complain about noise, smoke and parking. Those complaints are sometimes a proxy for who is seen to belong on the pavement after dark. A market that stays open until 02:00 on a street of new apartments will lose the political fight unless hours, extraction fans and a complaints number are negotiated before the first stall opens. Some cities now publish a one-page compact: hours, waste collection time, and a named officer. It is dull paperwork, and it is what keeps the lights on.

The writer does not romanticise every stall. Overcrowding, child labour and counterfeit goods appear where inspections are for show. The claim is that night markets are infrastructure, like a bus route: they move food, wages and people through hours when the formal city is closed. Pricing them as a festival, then being surprised when vendors cannot pay festival rents, is a policy error dressed as culture."""
